/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.oss.vaadinjooq.db;


import ch.martinelli.oss.vaadinjooq.db.tables.Customer;
import jakarta.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;
}
